#ifndef _SYSCONFIG_H
#define _SYSCONFIG_H

/************************************************************************
 *		        User Settings
 ************************************************************************/
/** User Settable */

/** Board Version */
//#define BOARD_VER_1_0         /**< Uncomment for PCB Version 1.0 */
//#define BOARD_VER_1_1         /**< Uncomment for PCB Version 1.1 */
#define BOARD_VER_1_3_2 /**< Uncomment for PCB Version 1.3.2 */

/** Test Cycle Settings */
#define TEST_RTC /**< Uncomment for Testing RTC Output */
//#define TEST_NO_RUN           /**< Uncomment to prevent run during alarm */
#define TEST_QUICK_PERIODS    /**< Uncomment to reduce the length of time of run */

/** Initialization Delay */
#define SYS_BOARD_INIT_DELAY (100) /** Startup delay (ms) */

/** Console Buffer Receive Length */
#define SYSTEM_CONSOLE_RX_BUFFER_LEN (128) /** Length of Console buffer */
#define SYSTEM_CONSOLE_RX_TIMEOUT (1500)   /** Console receive timeout (ms) */

/** Command Buffer Receive Length */
#define SYSTEM_COMMAND_RX_BUFFER_LEN (256) /** Length of Command buffer */
#define SYSTEM_COMMAND_RX_TIMEOUT (50)     /** Command receive timeout (ms) */

/** Default time settings.  Change to integer numbers to alter defaults */
#ifdef TEST_QUICK_PERIODS
#define DEFAULT_PCO2_NORM_START_YEAR (0)
#define DEFAULT_PCO2_NORM_START_MONTH (0)
#define DEFAULT_PCO2_NORM_START_DATE (0)
#define DEFAULT_PCO2_NORM_START_HOUR (0)
#define DEFAULT_PCO2_NORM_START_MINUTE (0)
#define DEFAULT_PCO2_NORM_START_SECOND (0)
#define DEFAULT_PCO2_NORM_INTERVAL_YEAR (0)
#define DEFAULT_PCO2_NORM_INTERVAL_MONTH (0)
#define DEFAULT_PCO2_NORM_INTERVAL_DATE (0)
#define DEFAULT_PCO2_NORM_INTERVAL_HOUR (0)
#define DEFAULT_PCO2_NORM_INTERVAL_MINUTE (10)
#define DEFAULT_PCO2_NORM_INTERVAL_SECOND (0)
#define DEFAULT_PCO2_FAST_INTERVAL_YEAR (0)
#define DEFAULT_PCO2_FAST_INTERVAL_MONTH (0)
#define DEFAULT_PCO2_FAST_INTERVAL_DATE (0)
#define DEFAULT_PCO2_FAST_INTERVAL_HOUR (0)
#define DEFAULT_PCO2_FAST_INTERVAL_MINUTE (4)
#define DEFAULT_PCO2_FAST_INTERVAL_SECOND (0)
#define DEFAULT_PCO2_FAST_CHANGE_YEAR (0)
#define DEFAULT_PCO2_FAST_CHANGE_MONTH (0)
#define DEFAULT_PCO2_FAST_CHANGE_DATE (0)
#define DEFAULT_PCO2_FAST_CHANGE_HOUR (3)
#define DEFAULT_PCO2_FAST_CHANGE_MINUTE (0)
#define DEFAULT_PCO2_FAST_CHANGE_SECOND (0)
#define DEFAULT_PCO2_FAST_LENGTH_YEAR (0)
#define DEFAULT_PCO2_FAST_LENGTH_MONTH (0)
#define DEFAULT_PCO2_FAST_LENGTH_DATE (0)
#define DEFAULT_PCO2_FAST_LENGTH_HOUR (0)
#define DEFAULT_PCO2_FAST_LENGTH_MINUTE (20)
#define DEFAULT_PCO2_FAST_LENGTH_SECOND (0)
#define DEFAULT_PCO2_RUN_LENGTH_YEAR (0)
#define DEFAULT_PCO2_RUN_LENGTH_MONTH (0)
#define DEFAULT_PCO2_RUN_LENGTH_DATE (0)
#define DEFAULT_PCO2_RUN_LENGTH_HOUR (20)
#define DEFAULT_PCO2_RUN_LENGTH_MINUTE (0)
#define DEFAULT_PCO2_RUN_LENGTH_SECOND (0)
#define DEFAULT_PCO2_O2_INTERVAL_YEAR (0)
#define DEFAULT_PCO2_O2_INTERVAL_MONTH (0)
#define DEFAULT_PCO2_O2_INTERVAL_DATE (1)
#define DEFAULT_PCO2_O2_INTERVAL_HOUR (0)
#define DEFAULT_PCO2_O2_INTERVAL_MINUTE (0)
#define DEFAULT_PCO2_O2_INTERVAL_SECOND (0)
#define DEFAULT_PCO2_O2_TIME_YEAR (0)
#define DEFAULT_PCO2_O2_TIME_MONTH (0)
#define DEFAULT_PCO2_O2_TIME_DATE (0)
#define DEFAULT_PCO2_O2_TIME_HOUR (23)
#define DEFAULT_PCO2_O2_TIME_MINUTE (45)
#define DEFAULT_PCO2_O2_TIME_SECOND (0)
#else
#ifndef TEST_NO_RUN
#define DEFAULT_PCO2_NORM_START_YEAR (0)
#define DEFAULT_PCO2_NORM_START_MONTH (0)
#define DEFAULT_PCO2_NORM_START_DATE (0)
#define DEFAULT_PCO2_NORM_START_HOUR (0)
#define DEFAULT_PCO2_NORM_START_MINUTE (0)
#define DEFAULT_PCO2_NORM_START_SECOND (0)
#define DEFAULT_PCO2_NORM_INTERVAL_YEAR (0)
#define DEFAULT_PCO2_NORM_INTERVAL_MONTH (0)
#define DEFAULT_PCO2_NORM_INTERVAL_DATE (0)
#define DEFAULT_PCO2_NORM_INTERVAL_HOUR (3)
#define DEFAULT_PCO2_NORM_INTERVAL_MINUTE (0)
#define DEFAULT_PCO2_NORM_INTERVAL_SECOND (0)
#define DEFAULT_PCO2_FAST_INTERVAL_YEAR (0)
#define DEFAULT_PCO2_FAST_INTERVAL_MONTH (0)
#define DEFAULT_PCO2_FAST_INTERVAL_DATE (0)
#define DEFAULT_PCO2_FAST_INTERVAL_HOUR (1)
#define DEFAULT_PCO2_FAST_INTERVAL_MINUTE (0)
#define DEFAULT_PCO2_FAST_INTERVAL_SECOND (0)
#define DEFAULT_PCO2_FAST_CHANGE_YEAR (0)
#define DEFAULT_PCO2_FAST_CHANGE_MONTH (0)
#define DEFAULT_PCO2_FAST_CHANGE_DATE (0)
#define DEFAULT_PCO2_FAST_CHANGE_HOUR (3)
#define DEFAULT_PCO2_FAST_CHANGE_MINUTE (0)
#define DEFAULT_PCO2_FAST_CHANGE_SECOND (0)
#define DEFAULT_PCO2_FAST_LENGTH_YEAR (0)
#define DEFAULT_PCO2_FAST_LENGTH_MONTH (0)
#define DEFAULT_PCO2_FAST_LENGTH_DATE (0)
#define DEFAULT_PCO2_FAST_LENGTH_HOUR (0)
#define DEFAULT_PCO2_FAST_LENGTH_MINUTE (20)
#define DEFAULT_PCO2_FAST_LENGTH_SECOND (0)
#define DEFAULT_PCO2_RUN_LENGTH_YEAR (0)
#define DEFAULT_PCO2_RUN_LENGTH_MONTH (0)
#define DEFAULT_PCO2_RUN_LENGTH_DATE (0)
#define DEFAULT_PCO2_RUN_LENGTH_HOUR (20)
#define DEFAULT_PCO2_RUN_LENGTH_MINUTE (0)
#define DEFAULT_PCO2_RUN_LENGTH_SECOND (0)
#define DEFAULT_PCO2_O2_INTERVAL_YEAR (0)
#define DEFAULT_PCO2_O2_INTERVAL_MONTH (0)
#define DEFAULT_PCO2_O2_INTERVAL_DATE (1)
#define DEFAULT_PCO2_O2_INTERVAL_HOUR (0)
#define DEFAULT_PCO2_O2_INTERVAL_MINUTE (0)
#define DEFAULT_PCO2_O2_INTERVAL_SECOND (0)
#define DEFAULT_PCO2_O2_TIME_YEAR (0)
#define DEFAULT_PCO2_O2_TIME_MONTH (0)
#define DEFAULT_PCO2_O2_TIME_DATE (0)
#define DEFAULT_PCO2_O2_TIME_HOUR (23)
#define DEFAULT_PCO2_O2_TIME_MINUTE (45)
#define DEFAULT_PCO2_O2_TIME_SECOND (0)

#else
#define DEFAULT_PCO2_NORM_START_YEAR (0)
#define DEFAULT_PCO2_NORM_START_MONTH (0)
#define DEFAULT_PCO2_NORM_START_DATE (0)
#define DEFAULT_PCO2_NORM_START_HOUR (0)
#define DEFAULT_PCO2_NORM_START_MINUTE (0)
#define DEFAULT_PCO2_NORM_START_SECOND (0)
#define DEFAULT_PCO2_NORM_INTERVAL_YEAR (0)
#define DEFAULT_PCO2_NORM_INTERVAL_MONTH (0)
#define DEFAULT_PCO2_NORM_INTERVAL_DATE (0)
#define DEFAULT_PCO2_NORM_INTERVAL_HOUR (0)
#define DEFAULT_PCO2_NORM_INTERVAL_MINUTE (1)
#define DEFAULT_PCO2_NORM_INTERVAL_SECOND (0)
#define DEFAULT_PCO2_FAST_INTERVAL_YEAR (0)
#define DEFAULT_PCO2_FAST_INTERVAL_MONTH (0)
#define DEFAULT_PCO2_FAST_INTERVAL_DATE (0)
#define DEFAULT_PCO2_FAST_INTERVAL_HOUR (0)
#define DEFAULT_PCO2_FAST_INTERVAL_MINUTE (1)
#define DEFAULT_PCO2_FAST_INTERVAL_SECOND (0)
#define DEFAULT_PCO2_FAST_CHANGE_YEAR (0)
#define DEFAULT_PCO2_FAST_CHANGE_MONTH (0)
#define DEFAULT_PCO2_FAST_CHANGE_DATE (0)
#define DEFAULT_PCO2_FAST_CHANGE_HOUR (0)
#define DEFAULT_PCO2_FAST_CHANGE_MINUTE (3)
#define DEFAULT_PCO2_FAST_CHANGE_SECOND (0)
#define DEFAULT_PCO2_FAST_LENGTH_YEAR (0)
#define DEFAULT_PCO2_FAST_LENGTH_MONTH (0)
#define DEFAULT_PCO2_FAST_LENGTH_DATE (0)
#define DEFAULT_PCO2_FAST_LENGTH_HOUR (0)
#define DEFAULT_PCO2_FAST_LENGTH_MINUTE (20)
#define DEFAULT_PCO2_FAST_LENGTH_SECOND (0)
#define DEFAULT_PCO2_RUN_LENGTH_YEAR (0)
#define DEFAULT_PCO2_RUN_LENGTH_MONTH (0)
#define DEFAULT_PCO2_RUN_LENGTH_DATE (0)
#define DEFAULT_PCO2_RUN_LENGTH_HOUR (20)
#define DEFAULT_PCO2_RUN_LENGTH_MINUTE (0)
#define DEFAULT_PCO2_RUN_LENGTH_SECOND (0)
#define DEFAULT_PCO2_O2_INTERVAL_YEAR (0)
#define DEFAULT_PCO2_O2_INTERVAL_MONTH (0)
#define DEFAULT_PCO2_O2_INTERVAL_DATE (1)
#define DEFAULT_PCO2_O2_INTERVAL_HOUR (0)
#define DEFAULT_PCO2_O2_INTERVAL_MINUTE (0)
#define DEFAULT_PCO2_O2_INTERVAL_SECOND (0)
#define DEFAULT_PCO2_O2_TIME_YEAR (0)
#define DEFAULT_PCO2_O2_TIME_MONTH (0)
#define DEFAULT_PCO2_O2_TIME_DATE (0)
#define DEFAULT_PCO2_O2_TIME_HOUR (23)
#define DEFAULT_PCO2_O2_TIME_MINUTE (45)
#define DEFAULT_PCO2_O2_TIME_SECOND (0)
#endif
#endif

#define DEFAULT_PCO2_EQUIL_QUICK (0)
#define DEFAULT_PCO2_PREQUIL_QUICK (0)
#define DEFAULT_PCO2_PUMPON_QUICK (0)
#define DEFAULT_PCO2_PUMPOFF_QUICK (0)
#define DEFAULT_PCO2_SAMPLECO2_QUICK (1)
#define DEFAULT_PCO2_LI_WARMUP_QUICK (0)
#define DEFAULT_PCO2_LI_HEATER_QUICK (0)
#define DEFAULT_PCO2_VENT_QUICK (0)

#define DEFAULT_PCO2_EQUIL (600)
#define DEFAULT_PCO2_PREQUIL (600)
#define DEFAULT_PCO2_PUMPON (30)
#define DEFAULT_PCO2_PUMPOFF (15)
#define DEFAULT_PCO2_SPANFLOWON (30)
#define DEFAULT_PCO2_PURGE (15)
#define DEFAULT_PCO2_SAMPLECO2 (30)
#define DEFAULT_PCO2_LI_WARMUP (30)
#define DEFAULT_PCO2_LI_HEATER (0)
#define DEFAULT_PCO2_VENT (10)

#define VENT_CLOSE_STABILIZE_TIME (2)
#define DEFAULT_PCO2_SPANDIFF (1.7)
#define DEFAULT_PCO2_SPAN (300.0)
#define DEFAULT_PCO2_SPAN2 (2000.0)
#define DEFAULT_PCO2_SAMPLE_FREQ (2)

/** Scheduler */
//#define INCLUDE_SCHEDULER_COMMANDS

/** TELOS */
#define INCLUDE_TELOS_COMMANDS (1)
#define SYS_IRIDIUM_BUFFER_HEADER_LENGTH (7)
#define SYS_IRIDIUM_MSG_BUFFER_LENGTH (1024)
#define SYS_IRIDIUM_BUFFER_LENGTH (SYS_IRIDIUM_MSG_BUFFER_LENGTH + SYS_IRIDIUM_BUFFER_HEADER_LENGTH)

/** Low Power Pin Configurations */
#define LPM_ALL_PINS (GPIO_PIN0 | GPIO_PIN1 | GPIO_PIN2 | GPIO_PIN3 | GPIO_PIN4 | GPIO_PIN5 | GPIO_PIN6 | GPIO_PIN7)

/** Port 1 */
#define LPM_PORT1_OUTPUT_HIGH_PINS (GPIO_PIN3 | GPIO_PIN6 | GPIO_PIN7)
#define LPM_PORT1_OUTPUT_LOW_PINS (GPIO_PIN0 | GPIO_PIN1)
#define LPM_PORT1_INPUT_WITH_PULL_UPS (GPIO_PIN4 | GPIO_PIN5)
#define LPM_PORT1_INPUT_WITH_PULL_DOWNS (NULL)
#define LPM_PORT1_INPUT_NO_RESISTORS (GPIO_PIN2)
#define LPM_PORT1_HIGH_TO_LOW_PINS (GPIO_PIN1 | GPIO_PIN3 | GPIO_PIN4 | GPIO_PIN5)
#define LPM_PORT1_LOW_TO_HIGH_PINS (NULL)

/** Port 2 */
#define LPM_PORT2_OUTPUT_HIGH_PINS (GPIO_PIN2)
#define LPM_PORT2_OUTPUT_LOW_PINS (GPIO_PIN3 | GPIO_PIN4 | GPIO_PIN5)
#define LPM_PORT2_INPUT_WITH_PULL_UPS (GPIO_PIN6 | GPIO_PIN7)
#define LPM_PORT2_INPUT_WITH_PULL_DOWNS (NULL)
#define LPM_PORT2_INPUT_NO_RESISTORS (NULL)
#define LPM_PORT2_HIGH_TO_LOW_PINS (GPIO_PIN7)
#define LPM_PORT2_LOW_TO_HIGH_PINS (NULL)

/** Port 3 */
#define LPM_PORT3_OUTPUT_HIGH_PINS (NULL)
#define LPM_PORT3_OUTPUT_LOW_PINS (GPIO_PIN0 | GPIO_PIN1 | GPIO_PIN2 | GPIO_PIN3 | GPIO_PIN4 | GPIO_PIN5 | GPIO_PIN6 | GPIO_PIN7)
#define LPM_PORT3_INPUT_WITH_PULL_UPS (NULL)
#define LPM_PORT3_INPUT_WITH_PULL_DOWNS (NULL)
#define LPM_PORT3_INPUT_NO_RESISTORS (NULL)
#define LPM_PORT3_HIGH_TO_LOW_PINS (NULL)
#define LPM_PORT3_LOW_TO_HIGH_PINS (NULL)

/** Port 4 */
#define LPM_PORT4_OUTPUT_HIGH_PINS (NULL)
#define LPM_PORT4_OUTPUT_LOW_PINS (GPIO_PIN0 | GPIO_PIN1 | GPIO_PIN2 | GPIO_PIN3 | GPIO_PIN4 | GPIO_PIN5 | GPIO_PIN6 | GPIO_PIN7)
#define LPM_PORT4_INPUT_WITH_PULL_UPS (NULL)
#define LPM_PORT4_INPUT_WITH_PULL_DOWNS (GPIO_PIN0 | GPIO_PIN4)
#define LPM_PORT4_INPUT_NO_RESISTORS (NULL)
#define LPM_PORT4_HIGH_TO_LOW_PINS (NULL)
#define LPM_PORT4_LOW_TO_HIGH_PINS (NULL)

/** Port 5 */
#define LPM_PORT5_OUTPUT_HIGH_PINS (GPIO_PIN0 | GPIO_PIN1 | GPIO_PIN6)
#define LPM_PORT5_OUTPUT_LOW_PINS (GPIO_PIN2 | GPIO_PIN3 | GPIO_PIN4 | GPIO_PIN5 | GPIO_PIN7)
#define LPM_PORT5_INPUT_WITH_PULL_UPS (NULL)
#define LPM_PORT5_INPUT_WITH_PULL_DOWNS (NULL)
#define LPM_PORT5_INPUT_NO_RESISTORS (NULL)
#define LPM_PORT5_HIGH_TO_LOW_PINS (NULL)
#define LPM_PORT5_LOW_TO_HIGH_PINS (NULL)

/** Port 6 */
#define LPM_PORT6_OUTPUT_HIGH_PINS (NULL)
#define LPM_PORT6_OUTPUT_LOW_PINS (GPIO_PIN0 | GPIO_PIN1 | GPIO_PIN2 | GPIO_PIN3 | GPIO_PIN4 | GPIO_PIN5 | GPIO_PIN6 | GPIO_PIN7)
#define LPM_PORT6_INPUT_WITH_PULL_UPS (NULL)
#define LPM_PORT6_INPUT_WITH_PULL_DOWNS (NULL)
#define LPM_PORT6_INPUT_NO_RESISTORS (NULL)
#define LPM_PORT6_HIGH_TO_LOW_PINS (NULL)
#define LPM_PORT6_LOW_TO_HIGH_PINS (NULL)

/** Port 7 */
#define LPM_PORT7_OUTPUT_HIGH_PINS (GPIO_PIN3 | GPIO_PIN4)
#define LPM_PORT7_OUTPUT_LOW_PINS (GPIO_PIN0 | GPIO_PIN1 | GPIO_PIN2 | GPIO_PIN5 | GPIO_PIN6 | GPIO_PIN7)
#define LPM_PORT7_INPUT_WITH_PULL_UPS (NULL)
#define LPM_PORT7_INPUT_WITH_PULL_DOWNS (NULL)
#define LPM_PORT7_INPUT_NO_RESISTORS (NULL)
#define LPM_PORT7_HIGH_TO_LOW_PINS (NULL)
#define LPM_PORT7_LOW_TO_HIGH_PINS (NULL)

/** Port 8 */
#define LPM_PORT8_OUTPUT_HIGH_PINS (NULL)
#define LPM_PORT8_OUTPUT_LOW_PINS (GPIO_PIN0 | GPIO_PIN1 | GPIO_PIN2 | GPIO_PIN3)
#define LPM_PORT8_INPUT_WITH_PULL_UPS (NULL)
#define LPM_PORT8_INPUT_WITH_PULL_DOWNS (NULL)
#define LPM_PORT8_INPUT_NO_RESISTORS (NULL)
#define LPM_PORT8_HIGH_TO_LOW_PINS (NULL)
#define LPM_PORT8_LOW_TO_HIGH_PINS (NULL)

/************************************************************************
 *		        MACROS
 ************************************************************************/
/** EUSCI Ports */
#define PORT_A0 (0x01)
#define PORT_A1 (0x02)
#define PORT_A2 (0x04)
#define PORT_A3 (0x08)
#define PORT_B0 (0x10)
#define PORT_B1 (0x20)
#define PORT_B2 (0x40)
#define PORT_B3 (0x80)

/** ADC Channels */
#define ADC_0 (0x0001)
#define ADC_1 (0x0002)
#define ADC_2 (0x0004)
#define ADC_3 (0x0008)
#define ADC_4 (0x0010)
#define ADC_5 (0x0020)
#define ADC_6 (0x0040)
#define ADC_7 (0x0080)
#define ADC_8 (0x0100)
#define ADC_9 (0x0200)
#define ADC_10 (0x0400)
#define ADC_11 (0x0800)
#define ADC_12 (0x1000)

/************************************************************************
 *						    SYSTEM CLOCKS
 ************************************************************************/

/** Crystal Frequencies */
#define HFXT_FREQ (7372800)
#define HFXT_DRIVE (HFXTDRIVE_0)
#define HFXT_TIMEOUT (HFXT_FREQ / 10)

#define LFXT_FREQ (0u)
#define LFXT_DRIVE (LFXTDRIVE_0)
#define LFXT_TIMEOUT (LFXT_FREQ)

/** Master Clock */
#define MCLK_DIV (CS_CLOCK_DIVIDER_2)
#define MCLK_SRC (CS_HFXTCLK_SELECT)
#define MCLK_FREQ (HFXT_FREQ / 1)
#define MCLK_DRIVE (HFXTDRIVE_2)

/** Subsystem Master Clock */
#define SMCLK_DIV (CS_CLOCK_DIVIDER_1)
#define SMCLK_SRC (CS_HFXTCLK_SELECT)
#define SMCLK_FREQ (HFXT_FREQ / 1)

/** Auxiliary Clock */
#define ACLK_DIV (CS_CLOCK_DIVIDER_1)
#define ACLK_SRC (CS_VLOCLK_SELECT)
#define ACLK_FREQ (10000)

/** Module Clock */
#define MODOSC_DIV (32)
#define MODOSC_SRC (SELM__HFXTCLK)
#define MODOSC_FREQ (HFXT_FREQ / 32)

/** HF Crystal GPIO Function Configurations */
#define HF_XTAL_PORT (GPIO_PORT_PJ)
#define HF_XTAL_PIN (GPIO_PIN6)
#define HF_XTAL_FUNCTION (GPIO_PRIMARY_MODULE_FUNCTION)

/************************************************************************
 *							SYSTEM TIMERS
 ************************************************************************/
/** Timer A */
#define TIMER_A_PERIOD (50000) /** USER SETTING */
#define SYS_TIMER_A_BASEADDRESS (TIMER_A0_BASE)
#define SYS_TIMER_A_CLOCKSOURCE (TIMER_A_CLOCKSOURCE_ACLK)
#define SYS_TIMER_A_CLKSRC_DIVIDER (TIMER_A_CLOCKSOURCE_DIVIDER_1)
#define SYS_TIMER_A_TIMER_PERIOD (TIMER_A_PERIOD)
#define SYS_TIMER_A_TBIE_INTERRUPT_DISABLE (TIMER_A_TBIE_INTERRUPT_DISABLE)
#define SYS_TIMER_A_CAPTURECOMPARE_INTERRUPT_ENABLE (TIMER_A_CAPTURECOMPARE_INTERRUPT_ENABLE)
#define SYS_TIMER_A_DO_CLEAR (TIMER_A_DO_CLEAR)

/** Timer B */
#define TIMER_B_PERIOD (50000) /** USER SETTING */
#define SYS_TIMER_B_BASEADDRESS (TIMER_B0_BASE)
#define SYS_TIMER_B_CLOCKSOURCE (TIMER_B_CLOCKSOURCE_ACLK)
#define SYS_TIMER_B_CLKSRC_DIVIDER (TIMER_B_CLOCKSOURCE_DIVIDER_1)
#define SYS_TIMER_B_TIMER_PERIOD (TIMER_B_PERIOD)
#define SYS_TIMER_B_TBIE_INTERRUPT_DISABLE (TIMER_B_TBIE_INTERRUPT_DISABLE)
#define SYS_TIMER_B_CAPTURECOMPARE_INTERRUPT_ENABLE (TIMER_B_CAPTURECOMPARE_INTERRUPT_ENABLE)
#define SYS_TIMER_B_DO_CLEAR (TIMER_B_DO_CLEAR)

/************************************************************************
 *							    UART
 ************************************************************************/
/** UART MACROS */
#define UART_ACK (0x06)
#define UART_NACK (0x15)
#define UART_ENDLINE ("\r\n")
#define SYS_UART_BUFFER_LEN (80)

/** UART A0 Setup */
#define UART_A0_TX_PORT (GPIO_PORT_P2)
#define UART_A0_TX_PIN (GPIO_PIN0)
#define UART_A0_RX_PORT (GPIO_PORT_P2)
#define UART_A0_RX_PIN (GPIO_PIN1)
#define UART_A0_FUNCTION (GPIO_SECONDARY_MODULE_FUNCTION)

/** UART A1 Setup */
#define UART_A1_TX_PORT (GPIO_PORT_P2)
#define UART_A1_TX_PIN (GPIO_PIN5)
#define UART_A1_RX_PORT (GPIO_PORT_P2)
#define UART_A1_RX_PIN (GPIO_PIN6)
#define UART_A1_FUNCTION (GPIO_SECONDARY_MODULE_FUNCTION)

/** UART A2 Setup */
#define UART_A2_TX_PORT (GPIO_PORT_P5)
#define UART_A2_TX_PIN (GPIO_PIN4)
#define UART_A2_RX_PORT (GPIO_PORT_P5)
#define UART_A2_RX_PIN (GPIO_PIN5)
#define UART_A2_FUNCTION (GPIO_PRIMARY_MODULE_FUNCTION)

/** UART A3 Setup */
#define UART_A3_TX_PORT (GPIO_PORT_P6)
#define UART_A3_TX_PIN (GPIO_PIN0)
#define UART_A3_RX_PORT (GPIO_PORT_P6)
#define UART_A3_RX_PIN (GPIO_PIN1)
#define UART_A3_FUNCTION (GPIO_PRIMARY_MODULE_FUNCTION)

/** Console UART configurations */
#define SYS_CONSOLE_UART_PORT (EUSCI_A0_BASE)
#define SYS_CONSOLE_UART_CLK (UCSSEL__SMCLK)
#define SYS_CONSOLE_UART_CLK_FREQ (SMCLK_FREQ)
#define SYS_CONSOLE_UART_BAUDRATE (115200) /** USER SETTING */
#define SYS_CONSOLE_PORT_CONFIG1() (P2SEL1 |= (BIT0 | BIT1))
#define SYS_CONSOLE_PORT_CONFIG0() (P2SEL0 &= ~(BIT0 | BIT1))
#define SYS_CONSOLE_UART_PARITY (EUSCI_A_UART_EVEN_PARITY)
#define SYS_CONSOLE_UART_MSB_FIRST (EUSCI_A_UART_LSB_FIRST)
#define SYS_CONSOLE_UART_STOPBITS (EUSCI_A_UART_ONE_STOP_BIT)
#define SYS_CONSOLE_UART_MODE (EUSCI_A_UART_MODE)

/** Command UART configurations */
#define SYS_COMMAND_UART_PORT (EUSCI_A1_BASE)
#define SYS_COMMAND_UART_CLK (UCSSEL__SMCLK)
#define SYS_COMMAND_UART_CLK_FREQ (SMCLK_FREQ)
#define SYS_COMMAND_UART_BAUDRATE (115200) /** USER SETTING */
#define SYS_COMMAND_PORT_CONFIG1() (P2SEL1 |= (BIT5 | BIT6))
#define SYS_COMMAND_PORT_CONFIG0() (P2SEL0 &= ~(BIT5 | BIT6))
#define SYS_COMMAND_UART_PARITY (EUSCI_A_UART_EVEN_PARITY)
#define SYS_COMMAND_UART_MSB_FIRST (EUSCI_A_UART_LSB_FIRST)
#define SYS_COMMAND_UART_STOPBITS (EUSCI_A_UART_ONE_STOP_BIT)
#define SYS_COMMAND_UART_MODE (EUSCI_A_UART_MODE)

/************************************************************************
 *							    GPIO
 ************************************************************************/
/** GPIO Macros */
#define PIN_OUT (0)
#define PIN_IN (1)
#define PIN_POLARITY_NORMAL (0)
#define PIN_POLARITY_REVERSE (1)

/** Command Power configurations */
#define CMD_POWER_PORT (GPIO_PORT_P2)
#define CMD_POWER_PIN (GPIO_PIN3)
#define CMD_POWER_DIR (PIN_OUT)
#define CMD_POWER_POL (PIN_POLARITY_NORMAL)

/** USB Detect configurations */
#define USB_DETECT_PORT (GPIO_PORT_P2)
#define USB_DETECT_PIN (GPIO_PIN7)
#define USB_DETECT_DIR (PIN_IN)
#define USB_DETECT_POL (PIN_POLARITY_NORMAL)

/** CMD Detect configurations */
#define CMD_DETECT_PORT (GPIO_PORT_P3)
#define CMD_DETECT_PIN (GPIO_PIN1)
#define CMD_DETECT_DIR (PIN_IN)
#define CMD_DETECT_POL (PIN_POLARITY_NORMAL)

/** Watchdog Pin */
#define WATCHDOG_PORT (GPIO_PORT_P4)
#define WATCHDOG_PIN (GPIO_PIN7)
#define WATCHDOG_DIR (PIN_OUT)
#define WATCHDOG_POL (PIN_POLARITY_NORMAL)

/** Oscillator Power Pin */
#define OSC_POWER_PORT (GPIO_PORT_P6)
#define OSC_POWER_PIN (GPIO_PIN7)
#define OSC_POWER_DIR (PIN_OUT)
#define OSC_POWER_POL (PIN_POLARITY_NORMAL)

/** Voltage Reference Pin */
#define VREF_POWER_PORT (GPIO_PORT_P4)
#define VREF_POWER_PIN (GPIO_PIN1)
#define VREF_POWER_DIR (PIN_OUT)
#define VREF_POWER_POL (PIN_POLARITY_NORMAL)

/** OptoRelay GPIO Configurations   */
#define SPARE_RS232_ENABLE_PORT (GPIO_PORT_P4)
#define SPARE_RS232_ENABLE_PIN (GPIO_PIN4)
#define SPARE_RS232_ENABLE_DIR (PIN_OUT)
#define SPARE_RS232_ENABLE_POL (PIN_POLARITY_NORMAL)

/** Peripheral Power 15V Pin */
#define POWER_15_ENABLE_PORT (GPIO_PORT_P5)
#define POWER_15_ENABLE_PIN (GPIO_PIN7)
#define POWER_15_ENABLE_DIR (PIN_OUT)
#define POWER_15_ENABLE_POL (PIN_POLARITY_NORMAL)

#ifdef BOARD_VER_1_3_2
/** Peripheral Power 15V PWM/SYNC Pin */
#define POWER_15_PWM_PORT (GPIO_PORT_P5)
#define POWER_15_PWM_PIN (GPIO_PIN3)
#define POWER_15_PWM_DIR (PIN_OUT)
#define POWER_15_PWM_POL (PIN_POLARITY_NORMAL)
#endif

/** Flow Control Enable GPIO */
#define FLOWCTRL_ENABLE_PORT (GPIO_PORT_P4)
#define FLOWCTRL_ENABLE_PIN (GPIO_PIN5)
#define FLOWCTRL_ENABLE_DIR (PIN_OUT)
#define FLOWCTRL_ENABLE_POL (PIN_POLARITY_NORMAL)

/** Licor Enable GPIO */
#define LICOR_ENABLE_PORT (GPIO_PORT_P5)
#define LICOR_ENABLE_PIN (GPIO_PIN6)
#define LICOR_ENABLE_DIR (PIN_OUT)
#define LICOR_ENABLE_POL (PIN_POLARITY_REVERSE)

/** LED GPIO Configurations */
#define GREEN_LED_PORT (GPIO_PORT_P8)
#define GREEN_LED_PIN (GPIO_PIN2)
#define GREEN_LED_DIR (PIN_OUT)
#define GREEN_LED_POL (PIN_POLARITY_NORMAL)

#define RED_LED_PORT (GPIO_PORT_P8)
#define RED_LED_PIN (GPIO_PIN3)
#define RED_LED_DIR (PIN_OUT)
#define RED_LED_POL (PIN_POLARITY_NORMAL)

/** Other Peripheral GPIO Configurations */
#define WATCHDOG_PORT (GPIO_PORT_P4)
#define WATCHDOG_PIN (GPIO_PIN7)
#define WATCHDOG_DIR (PIN_OUT)
#define WATCHDOG_POL (PIN_POLARITY_NORMAL)

/** Micro Oscillator Power Toggle GPIO */
#define OSC_POWER_PORT (GPIO_PORT_P6)
#define OSC_POWER_PIN (GPIO_PIN7)
#define OSC_POWER_DIR (PIN_OUT)
#define OSC_POWER_POL (PIN_POLARITY_NORMAL)

/** Analog VREF Power Toggle GPIO */
#define VREF_POWER_PORT (GPIO_PORT_P4)
#define VREF_POWER_PIN (GPIO_PIN1)
#define VREF_POWER_DIR (PIN_OUT)
#define VREF_POWER_POL (PIN_POLARITY_NORMAL)

/** Debug Port GPIO */
#define DEBUG_GPIO0_PORT (GPIO_PORT_P6)
#define DEBUG_GPIO0_PIN (GPIO_PIN2)
#define DEBUG_GPIO0_DIR (PIN_OUT)
#define DEBUG_GPIO0_POL (PIN_POLARITY_NORMAL)

#define DEBUG_GPIO1_PORT (GPIO_PORT_P6)
#define DEBUG_GPIO1_PIN (GPIO_PIN3)
#define DEBUG_GPIO1_DIR (PIN_OUT)
#define DEBUG_GPIO1_POL (PIN_POLARITY_NORMAL)

/************************************************************************
 *		                ALTERNATIVE FUNCTION GPIO
 ************************************************************************/
/** SPI and I2C Configuartions */
#define I2C_B0_SDA_PORT (GPIO_PORT_P1)
#define I2C_B0_SDA_PIN (GPIO_PIN7)
#define I2C_B0_SCL_PORT (GPIO_PORT_P1)
#define I2C_B0_SCL_PIN (GPIO_PIN6)
#define I2C_B0_FUNCTION (GPIO_SECONDARY_MODULE_FUNCTION)

#define I2C_B1_SDA_PORT (GPIO_PORT_P5)
#define I2C_B1_SDA_PIN (GPIO_PIN0)
#define I2C_B1_SCL_PORT (GPIO_PORT_P5)
#define I2C_B1_SCL_PIN (GPIO_PIN1)
#define I2C_B1_FUNCTION (GPIO_PRIMARY_MODULE_FUNCTION)

#define SPI_B2_MOSI_PORT (GPIO_PORT_P7)
#define SPI_B2_MOSI_PIN (GPIO_PIN0)
#define SPI_B2_MISO_PORT (GPIO_PORT_P7)
#define SPI_B2_MISO_PIN (GPIO_PIN1)
#define SPI_B2_CLK_PORT (GPIO_PORT_P7)
#define SPI_B2_CLK_PIN (GPIO_PIN2)
#define SPI_B2_FUNCTION (GPIO_PRIMARY_MODULE_FUNCTION)

/** SMCLK Frequency Test pin */
#define SMCLK_OUTPUT_PORT (GPIO_PORT_P3)
#define SMCLK_OUTPUT_PIN (GPIO_PIN4)
#define SMCLK_OUTPUT_DIR (PIN_OUT)
#define SMCLK_OUTPUT_POL (PIN_POLARITY_NORMAL)
#define SMCLK_OUTPUT_FUNCTION (GPIO_SECONDARY_MODULE_FUNCTION)

/** High Frequency Crystal Input */
#define HF_XTAL_PORT (GPIO_PORT_PJ)
#define HF_XTAL_PIN (GPIO_PIN6)
#define HF_XTAL_FUNCTION (GPIO_PRIMARY_MODULE_FUNCTION)

/************************************************************************
 *							    LICOR
 ************************************************************************/
/** LICOR 820/830 UART Configuration */
#define LICOR_UART_PORT (EUSCI_A2_BASE)
#define LICOR_UART_CLK (UCSSEL__SMCLK)
#define LICOR_UART_CLK_FREQ (SMCLK_FREQ)
#define LICOR_UART_BAUDRATE (9600)
#define LICOR_PORT_CONFIG1() (P5SEL1 |= (BIT4 | BIT5))
#define LICOR_PORT_CONFIG0() (P5SEL0 &= ~(BIT5 | BIT6))
#define LICOR_UART_PARITY (EUSCI_A_UART_EVEN_PARITY)
#define LICOR_UART_MSB_FIRST (EUSCI_A_UART_LSB_FIRST)
#define LICOR_UART_STOPBITS (EUSCI_A_UART_ONE_STOP_BIT)
#define LICOR_UART_MODE (EUSCI_A_UART_MODE)

/** LICOR Settings */
#define LICOR_CO2_OUTPUT (true)
#define LICOR_CO2ABS_OUTPUT (true)
#define LICOR_H2O_OUTPUT (true)
#define LICOR_DEWPOINT_OUTPUT (true)
#define LICOR_H2OABS_OUTPUT (true)
#define LICOR_CELLTEMP_OUTPUT (true)
#define LICOR_CELLPRES_OUTPUT (true)
#define LICOR_IVOLT_OUTPUT (true)
#define LICOR_ECHO_OUTPUT (true)

/** Licor UART Buffer */
#define LICOR_BUFFER_LEN (2048)

/************************************************************************
 *							    Datalogger
 ************************************************************************/
/** Datalogger UART Configuration */
#define SDL_UART_PORT (EUSCI_A3_BASE)
#define SDL_UART_CLK (UCSSEL__SMCLK)
#define SDL_UART_CLK_FREQ (SMCLK_FREQ)
#define SDL_UART_BAUDRATE (115200)
#define SDL_PORT_CONFIG1 (P6SEL1 |= (BIT0 | BIT1))
#define SDL_PORT_CONFIG0 (P6SEL0 &= ~(BIT0 | BIT1))
#define SDL_UART_PARITY (EUSCI_A_UART_EVEN_PARITY)
#define SDL_UART_MSB_FIRST (EUSCI_A_UART_LSB_FIRST)
#define SDL_UART_STOPBITS (EUSCI_A_UART_ONE_STOP_BIT)
#define SDL_UART_MODE (EUSCI_A_UART_MODE)

/************************************************************************
 *							    Flow Controller
 ************************************************************************/
/** Flow Controller Configuration */
#define FLOW_POWER_PORT (GPIO_PORT_P4)
#define FLOW_POWER_PIN (GPIO_PIN5)
#define FLOW_POWER_DIR (PIN_OUT)
#define FLOW_POWER_POL (PIN_POLARITY_NORMAL)
#define FLOW_UART_BAUDRATE (9600)

/************************************************************************
 *							    LEDs
 ************************************************************************/
//#define INCLUDE_LED_COMMANDS
//#define GREEN_LED
#define SYS_LED_GREEN_PORT (GPIO_PORT_P8)
#define SYS_LED_GREEN_PIN (GPIO_PIN2)

//#define RED_LED
#define SYS_LED_RED_PORT (GPIO_PORT_P8)
#define SYS_LED_RED_PIN (GPIO_PIN3)
/************************************************************************
 *							    RH Sensor
 ************************************************************************/
/** RH Sensor Configuration */
#define RH_TYPE (RH_BME680)
#define RH_I2C_PORT (EUSCI_B1_BASE)
#define RH_I2C_CLK_SRC (UCSSEL__SMCLK)
#define RH_I2C_CLK_FREQ (SMCLK_FREQ)
#define RH_I2C_CLK_DES_FREQ (EUSCI_B_I2C_SET_DATA_RATE_100KBPS)
#define RH_I2C_BYTE_CNT_THRESHOLD (0x01)
#define RH_I2C_AUTOSTOP (EUSCI_B_I2C_NO_AUTO_STOP)
#define RH_PORT_CONFIG1 (P5SEL1 |= (BIT0 | BIT1))
#define RH_PORT_CONFIG2 (P5SEL0 &= (BIT0 | BIT1))
#define RH_I2C_MODE (EUSCI_B_I2C_TRANSMIT_MODE)
#define RH_I2C_SLAVE_ADDR (0x44)
#define RH_I2C_TIMEOUT (100)

#define SHT35_I2C_CLK_SRC (RH_I2C_CLK_SRC)
#define SHT35_I2C_CLK_FREQ (RH_I2C_CLK_FREQ)
#define SHT35_I2C_DES_FREQ (RH_I2C_CLK_DES_FREQ)
#define SHT35_I2C_BYTE_CNT_THRESHOLD (RH_I2C_BYTE_CNT_THRESHOLD)
#define SHT35_I2C_AUTOSTOP (RH_I2C_AUTOSTOP)
#define SHT35_I2C_PORT (RH_I2C_PORT)
#define SHT35_I2C_MODE (RH_I2C_MODE)
#define SHT35_I2C_SLAVE_ADDR (RH_I2C_SLAVE_ADDR)
#define SHT35_I2C_TIMEOUT (RH_I2C_TIMEOUT)

/************************************************************************
 *							   SPI->UART Controller
 ************************************************************************/
/** MAX310X Configuration */
#define MAX310X_CRYSTAL_FREQUENCY (3686400)
#define MAX310X_DEFAULT_RATEMODE (1)
#define MAX310X_DEFAULT_BAUDRATE (9600)

#define MAX310X_SPI_PORT (EUSCI_B2_BASE)
#define MAX310X_SPI_CLK_SRC (EUSCI_A_SPI_CLOCKSOURCE_SMCLK)
#define MAX310X_SPI_CLK_FREQ (SMCLK_FREQ)
#define MAX310X_SPI_CLK_DES_FREQ (100000)
#define MAX310X_SPI_MSB_FIRST (EUSCI_A_SPI_MSB_FIRST)
#define MAX310X_SPI_CLK_PHASE (EUSCI_A_SPI_PHASE_DATA_CHANGED_ONFIRST_CAPTURED_ON_NEXT)
#define MAX310X_SPI_CLK_POL (EUSCI_B_SPI_CLOCKPOLARITY_INACTIVITY_HIGH)
#define MAX310X_SPI_CLK_MODE (EUSCI_A_SPI_3PIN)
#define MAX310X_RECEIVE_INTERRUPT_LEN (10)

/** MAX310X GPIO Configurations */
#define MAX310X_I2C_SEL_PORT (GPIO_PORT_P8)
#define MAX310X_I2C_SEL_PIN (GPIO_PIN0)
#define MAX310X_I2C_SEL_DIR (PIN_OUT)
#define MAX310X_I2C_SEL_POL (PIN_POLARITY_NORMAL)

#define MAX310X_NRESET_PORT (GPIO_PORT_P7)
#define MAX310X_NRESET_PIN (GPIO_PIN5)
#define MAX310X_NRESET_DIR (PIN_OUT)
#define MAX310X_NRESET_POL (PIN_POLARITY_REVERSE)

#define MAX310X_CS_PORT (GPIO_PORT_P7)
#define MAX310X_CS_PIN (GPIO_PIN3)
#define MAX310X_CS_DIR (PIN_OUT)
#define MAX310X_CS_POL (PIN_POLARITY_REVERSE)

#define MAX310X_NIRQ_PORT (GPIO_PORT_P7)
#define MAX310X_NIRQ_PIN (GPIO_PIN4)
#define MAX310X_NIRQ_DIR (PIN_OUT)
#define MAX310X_NIRQ_POL (PIN_POLARITY_REVERSE)

/************************************************************************
 *							   RTC
 ************************************************************************/
/** AMBIQ RTC -> MICROCONTROLLER SYSTICK FREQUENCY */
#define AMBIQ_RTC_SYSTICK_FREQ (16)
#define AMBIQ_RTC_SQW_SETTING (SQFS_16)

/** AMBIQ RTC Clock Frequency */
#define AMBIQ_RTC_CLK_FREQ (32768)
/** AMBIQ RTC Timer Interrupt Pin  */
#define AMBIQ_RTC_NTIRQ_PORT (GPIO_PORT_P1)
#define AMBIQ_RTC_NTIRQ_PIN (GPIO_PIN2)
#define AMBIQ_RTC_NTIRQ_DIR (PIN_IN)
#define AMBIQ_RTC_NTIRQ_POL (PIN_POLARITY_REVERSE)

/** AMBIQ RTC EXT Pin */
#define AMBIQ_RTC_EXT_PORT (GPIO_PORT_P1)
#define AMBIQ_RTC_EXT_PIN (GPIO_PIN3)
#define AMBIQ_RTC_EXT_DIR (PIN_IN)
#define AMBIQ_RTC_EXT_POL (PIN_POLARITY_NORMAL)

/** AMBIQ RTC Interrupt 1 Pin */
#define AMBIQ_RTC_NIRQ1_PORT (GPIO_PORT_P1)
#define AMBIQ_RTC_NIRQ1_PIN (GPIO_PIN4)
#define AMBIQ_RTC_NIRQ1_DIR (PIN_IN)
#define AMBIQ_RTC_NIRQ1_POL (PIN_POLARITY_REVERSE)

/** AMBIQ RTC Interrupt 2 Pin */
#define AMBIQ_RTC_NIRQ2_PORT (GPIO_PORT_P1)
#define AMBIQ_RTC_NIRQ2_PIN (GPIO_PIN5)
#define AMBIQ_RTC_NIRQ2_DIR (PIN_IN)
#define AMBIQ_RTC_NIRQ2_POL (PIN_POLARITY_REVERSE)

/** Ambiq RTC Configuration */
#define AMBIQ_RTC_I2C_PORT (EUSCI_B0_BASE)
#define AMBIQ_RTC_I2C_CLK_SRC (EUSCI_B_I2C_CLOCKSOURCE_SMCLK)
#define AMBIQ_RTC_I2C_CLK_FREQ (SMCLK_FREQ)
#define AMBIQ_RTC_I2C_DES_FREQ (EUSCI_B_I2C_SET_DATA_RATE_100KBPS)
#define AMBIQ_RTC_PORT_CONFIG1 (P1SEL1 |= (BIT6 | BIT7))
#define AMBIQ_RTC_PORT_CONFIG2 (P1SEL0 &= (BIT6 | BIT7))
#define AMBIQ_RTC_I2C_MODE (EUSCI_B_I2C_TRANSMIT_MODE)
#define AMBIQ_RTC_I2C_BYTE_CNT_THRESHOLD (0x01)
#define AMBIQ_RTC_I2C_AUTOSTOP (EUSCI_B_I2C_NO_AUTO_STOP)
#define AMBIQ_RTC_I2C_SLAVE_ADDR (0xD2)
#define AMBIQ_RTC_I2C_TIMEOUT (0x000FFFFF)
#define SYSTEM_RTC_TIMEOUT_MS (250)
#define SYSTEM_RTC_ALARM_PIN (AM08X5_OUTPUT_NIRQ1)
#define SYSTEM_RTC_TIMER_PIN (AM08X5_OUTPUT_TIRQ)

/** AMBIQ RTC GPIO Configurations */
#define AMBIQ_RTC_NTIRQ_PORT (GPIO_PORT_P1)
#define AMBIQ_RTC_NTIRQ_PIN (GPIO_PIN2)
#define AMBIQ_RTC_NTIRQ_DIR (PIN_IN)
#define AMBIQ_RTC_NTIRQ_POL (PIN_POLARITY_REVERSE)

#define AMBIQ_RTC_EXT_PORT (GPIO_PORT_P1)
#define AMBIQ_RTC_EXT_PIN (GPIO_PIN3)
#define AMBIQ_RTC_EXT_DIR (PIN_IN)
#define AMBIQ_RTC_EXT_POL (PIN_POLARITY_NORMAL)

#define AMBIQ_RTC_NIRQ1_PORT (GPIO_PORT_P1)
#define AMBIQ_RTC_NIRQ1_PIN (GPIO_PIN4)
#define AMBIQ_RTC_NIRQ1_DIR (PIN_IN)
#define AMBIQ_RTC_NIRQ1_POL (PIN_POLARITY_REVERSE)

#define AMBIQ_RTC_NIRQ2_PORT (GPIO_PORT_P1)
#define AMBIQ_RTC_NIRQ2_PIN (GPIO_PIN5)
#define AMBIQ_RTC_NIRQ2_DIR (PIN_IN)
#define AMBIQ_RTC_NIRQ2_POL (PIN_POLARITY_REVERSE)

/** Ambiq AM0805 RTC Configurations */
#define SYSTEM_RTC_TIMEOUT_MS (250)
#define SYSTEM_RTC_ALARM_PIN (AM08X5_OUTPUT_NIRQ1)
#define SYSTEM_RTC_TIMER_PIN (AM08X5_OUTPUT_TIRQ)

/** RTC 1 Second Timer Config */
#define AMBIQ_RTC_TIMER_RANGE (1)
#define AMBIQ_RTC_TIMER_REPEAT (1)
#define AMBIQ_RTC_TIMER_PERIOD (1)

/************************************************************************
 *							  Oxygen Sensor
 ************************************************************************/
/** Analog Configurations */
#define ANALOG_SIG_PORT (ADC12_B_INPUT_A8)
#define ANALOG_SIG_CLK (ADC12_B_CLOCKSOURCE_SMCLK)
#define ANALOG_SIG_CLK_DIVIDER (ADC12_B_CLOCKPREDIVIDER__32)
#define ANALOG_SIG_VREF (ADC12_B_VREFPOS_EXTPOS_VREFNEG_VSS)
#define ANALOG_SIG_RESOLUTION (ADC12_B_RESOLUTION_12BIT)
#define ANALOG_SIG_INVERTED (ADC12_B_NONINVERTEDSIGNAL)
#define ANALOG_SIG_DIFFERENTIAL (ADC12_B_DIFFERENTIAL_MODE_DISABLE)
#define ANALOG_SIG_CYCLEHOLD (ADC12_B_CYCLEHOLD_64_CYCLES)
#define ANALOG_SIG_SAMPLEHOLD (ADC12_B_SAMPLEHOLDSOURCE_3)

/** ADC Config */
#define O2_ADC_REF_VOLTAGE (1.024)
#define O2_ADC_SRC (ADC12_B_SAMPLEHOLDSOURCE_SC)
#define O2_ADC_CLK_SRC (ADC12_B_CLOCKSOURCE_ACLK)
#define O2_ADC_CLK_DIVIDER (ADC12_B_CLOCKDIVIDER_1)
#define O2_ADC_CLK_PREDIVIDER (ADC12_B_CLOCKPREDIVIDER__1)
#define O2_ADC_INT_CHN_MAP (ADC12_B_MAPINTCH0)
#define O2_ADC_BUF_IDX (ADC12_B_MEMORY_0)
#define O2_ADC_SRC_SEL (ADC12_B_INPUT_A0)
#define O2_ADC_REF_VOLT_SRC_SEL (ADC12_B_VREFPOS_EXTPOS_VREFNEG_VSS)
#define O2_ADC_EOS (ADC12_B_ENDOFSEQUENCE)
#define O2_ADC_WIN_COMP_SEL (ADC12_B_WINDOW_COMPARATOR_DISABLE)
#define O2_ADC_DIFF_MODE_ENABLE (ADC12_B_DIFFERENTIAL_MODE_DISABLE)

#define O2_ANALOG_PORT (GPIO_PORT_P4)
#define O2_ANALOG_PIN (GPIO_PIN0)
#define O2_ANALOG_FUNCTION (GPIO_TERNARY_MODULE_FUNCTION)
#define O2_ANALOG_DIR (PIN_IN)
#define O2_ANALOG_POL (PIN_POLARITY_NORMAL)

#define O2_POWER_PORT (GPIO_PORT_P4)
#define O2_POWER_PIN (GPIO_PIN1)
#define O2_POWER_DIR (PIN_OUT)
#define O2_POWER_POL (PIN_POLARITY_NORMAL)

#define MAX250_CAL_DEFAULT (50.092f)
#define MAX250_MIN_VOLTAGE (0.010f)
#define MAX250_MAX_VOLTAGE (0.015f)

#endif /* _SYSCONFIG_H */